### ISSUE TITLE
Proposal: new config file format

### ISSUE THREAD

**Issue by tlambert03** [micro-manager/mmCoreAndDevices#630]
## Summary

Micro-Manager has used the same .cfg configuration file format for a while. While functional, this format has limitations:

1. Lacks formal schema validation
1. Limited structured hierarchy
1. Limited standardized commenting or documentation
1. Limited (no?) tooling support for editing and validation
1. Requires custom parsing logic

I propose implementing a modern, schema-validated, declarative configuration file format for Micro-Manager to replace the current procedural .cfg format. This would provide a more structured, validated approach to system configuration, allow a more human-readable file format, with clearer semantics, and would decouple the concept of what a system configuration file even is outside of the context of a C++ method.

## Proposal

In <https://github.com/tlambert03/mmcore-schema>, I'm stubbing out a JSON Schema definition that formalizes the configuration structure and enables the use of either JSON or YAML as the format for Micro-Manager configuration files. I'm defining it using pydantic (for convenience in exporting to json schema format ... not because it will actually require python).  The JSON schema as it currently stands is [here](https://github.com/tlambert03/mmcore-schema/blob/main/schemas/mmconfig/1.0/mmconfig.schema.json)  (pasted inline below for convenience)

<details>

<summary>current schema</summary>

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://micro-manager.org/schemas/mmconfig/1.0/mmconfig.schema.json",
  "title": "MMConfigFile",
  "type": "object",
  "properties": {
    "schema_version": {
      "const": "1.0",
      "default": "1.0",
      "description": "The version of the schema used to create this file. This is used to determine how to parse the file.",
      "title": "Schema Version",
      "type": "string"
    },
    "devices": {
      "description": "List of devices to load. Devices will be loaded in the order they are listed.",
      "items": {
        "$ref": "#/$defs/Device"
      },
      "title": "Devices",
      "type": "array"
    },
    "pre_init_properties": {
      "description": "List of properties to set on devices before device initialization. Properties will be set in the order they are listed.",
      "items": {
        "$ref": "#/$defs/DeviceProperty"
      },
      "title": "Pre Init Properties",
      "type": "array"
    },
    "post_init_properties": {
      "description": "List of properties to set on devices after device initialization. Properties will be set in the order they are listed.",
      "items": {
        "$ref": "#/$defs/DeviceProperty"
      },
      "title": "Post Init Properties",
      "type": "array"
    },
    "core_properties": {
      "$ref": "#/$defs/CoreProperties",
      "description": "Default properties to set on the Micro-Manager core."
    },
    "configuration_groups": {
      "description": "Configuration groups to create.",
      "items": {
        "$ref": "#/$defs/ConfigGroup"
      },
      "title": "Configuration Groups",
      "type": "array"
    },
    "pixel_size_configurations": {
      "description": "Pixel size configurations to create. These configurations will be used to set the pixel size of the camera.",
      "items": {
        "$ref": "#/$defs/PixelSizeConfiguration"
      },
      "title": "Pixel Size Configurations",
      "type": "array"
    },
    "extra": {
      "additionalProperties": true,
      "description": "User-defined extra properties. Not used by Micro-Manager.",
      "title": "Extra",
      "type": "object"
    }
  },
  "additionalProperties": false,
  "$defs": {
    "ConfigGroup": {
      "description": "A group of configuration presets.",
      "properties": {
        "name": {
          "description": "The name of the configuration group.",
          "title": "Name",
          "type": "string"
        },
        "configurations": {
          "description": "Configuration settings for the group. ",
          "items": {
            "$ref": "#/$defs/Configuration"
          },
          "title": "Configurations",
          "type": "array"
        }
      },
      "required": [
        "name"
      ],
      "title": "ConfigGroup",
      "type": "object"
    },
    "Configuration": {
      "description": "A group of device property settings.",
      "properties": {
        "name": {
          "description": "A name for this configuration. ",
          "title": "Name",
          "type": "string"
        },
        "settings": {
          "description": "List of settings to apply to the configuration. Settings will be applied in the order they are listed.",
          "items": {
            "$ref": "#/$defs/PropertySetting"
          },
          "title": "Settings",
          "type": "array"
        }
      },
      "required": [
        "name"
      ],
      "title": "Configuration",
      "type": "object"
    },
    "CoreProperties": {
      "properties": {
        "camera_device": {
          "default": null,
          "description": "The label of the device to use as the camera.",
          "title": "Camera Device",
          "type": [
            "string",
            "null"
          ]
        },
        "xy_stage_device": {
          "default": null,
          "description": "The label of the device to use as the XY stage.",
          "title": "Xy Stage Device",
          "type": [
            "string",
            "null"
          ]
        },
        "focus_device": {
          "default": null,
          "description": "The label of the device to use as the focus device.",
          "title": "Focus Device",
          "type": [
            "string",
            "null"
          ]
        },
        "auto_focus_device": {
          "default": null,
          "description": "The label of the device to use as the auto focus device.",
          "title": "Auto Focus Device",
          "type": [
            "string",
            "null"
          ]
        },
        "shutter_device": {
          "default": null,
          "description": "The label of the device to use as the shutter device.",
          "title": "Shutter Device",
          "type": [
            "string",
            "null"
          ]
        },
        "image_processor_device": {
          "default": null,
          "description": "The label of the device to use as the image processor device.",
          "title": "Image Processor Device",
          "type": [
            "string",
            "null"
          ]
        },
        "slm_device": {
          "default": null,
          "description": "The label of the device to use as the SLM device.",
          "title": "Slm Device",
          "type": [
            "string",
            "null"
          ]
        },
        "galvo_device": {
          "default": null,
          "description": "The label of the device to use as the galvo device.",
          "title": "Galvo Device",
          "type": [
            "string",
            "null"
          ]
        },
        "channel_group": {
          "default": null,
          "description": "Name of the configuration group that contains optical configuration (i.e. channel group) settings.",
          "title": "Channel Group",
          "type": [
            "string",
            "null"
          ]
        },
        "auto_shutter": {
          "default": null,
          "description": "Whether to enable the auto shutter feature.",
          "title": "Auto Shutter",
          "type": [
            "boolean",
            "null"
          ]
        },
        "timeout_ms": {
          "default": null,
          "description": "Default timeout for device actions, in milliseconds.",
          "title": "Timeout Ms",
          "type": [
            "integer",
            "null"
          ]
        }
      },
      "title": "CoreProperties",
      "type": "object"
    },
    "Device": {
      "properties": {
        "label": {
          "description": "The user-determined label to assign to the device",
          "title": "Label",
          "type": "string"
        },
        "library": {
          "description": "The adapter library that provides the device.",
          "title": "Library",
          "type": "string"
        },
        "name": {
          "description": "The name of the device to load from the library",
          "title": "Name",
          "type": "string"
        },
        "delay_ms": {
          "default": null,
          "description": "Delay, in milliseconds, for device acitons. (note: Some devices ignore this setting.)",
          "title": "Delay Ms",
          "type": [
            "number",
            "null"
          ]
        },
        "focus_direction": {
          "default": null,
          "description": "Focus direction (only applicable for Stage Devices, ignored otherwise). -1 = increasing position moves objective away from sample.  0 | None = unknown.  1 = increasing position moves objective towards sample. ",
          "title": "Focus Direction",
          "type": [
            "integer",
            "null"
          ]
        },
        "state_labels": {
          "default": null,
          "description": "A dictionary mapping state numbers to labels (only applicable for State Devices, ignored otherwise). Provides a human-readable label for each state of the device.",
          "title": "State Labels",
          "type": [
            "object",
            "null"
          ]
        }
      },
      "required": [
        "label",
        "library",
        "name"
      ],
      "title": "Device",
      "type": "object"
    },
    "DeviceProperty": {
      "properties": {
        "device_label": {
          "description": "The label of the device to set the property on",
          "title": "Device Label",
          "type": "string"
        },
        "property_name": {
          "description": "The name of the property to set on the device",
          "title": "Property Name",
          "type": "string"
        },
        "value": {
          "description": "The value to set for the property on the device",
          "title": "Value",
          "type": "string"
        }
      },
      "required": [
        "device_label",
        "property_name",
        "value"
      ],
      "title": "DeviceProperty",
      "type": "object"
    },
    "PixelSizeConfiguration": {
      "description": "Configuration of a pixel size.",
      "properties": {
        "name": {
          "description": "A name for this configuration. ",
          "title": "Name",
          "type": "string"
        },
        "settings": {
          "description": "List of settings to apply to the configuration. Settings will be applied in the order they are listed.",
          "items": {
            "$ref": "#/$defs/PropertySetting"
          },
          "title": "Settings",
          "type": "array"
        },
        "pixel_size_um": {
          "description": "Pixel size in micrometers. This is the size of a pixel in the image sensor of the camera.",
          "title": "Pixel Size Um",
          "type": "number"
        },
        "affine_matrix": {
          "default": null,
          "description": "Affine transformation matrix to apply to the configuration group. This is a 2x3 matrix represented as a tuple of 6 floats.",
          "title": "Affine Matrix",
          "type": [
            "array",
            "null"
          ]
        },
        "dxdz": {
          "default": null,
          "description": "The angle between the camera's x axis and the axis (direction)of the z drive for the given pixel size configuration. This angle isdimensionless (i.e. the ratio of the translation in x caused by a translation in z, i.e. dx / dz).",
          "title": "Dxdz",
          "type": [
            "number",
            "null"
          ]
        },
        "dydz": {
          "default": null,
          "description": "The angle between the camera's y axis and the axis (direction)of the z drive for the given pixel size configuration. This angle isdimensionless (i.e. the ratio of the translation in y caused by a translation in z, i.e. dy / dz).",
          "title": "Dydz",
          "type": [
            "number",
            "null"
          ]
        },
        "optimal_z_um": {
          "default": null,
          "description": "User-defined 'optimal' z step size for this pixel size configuration.",
          "title": "Optimal Z Um",
          "type": [
            "number",
            "null"
          ]
        }
      },
      "required": [
        "name",
        "pixel_size_um"
      ],
      "title": "PixelSizeConfiguration",
      "type": "object"
    },
    "PropertySetting": {
      "description": "A single device property setting.",
      "properties": {
        "device_label": {
          "description": "The label of the device to set the configuration on",
          "title": "Device Label",
          "type": "string"
        },
        "property_name": {
          "description": "The name of the property to set on the device",
          "title": "Property Name",
          "type": "string"
        },
        "value": {
          "description": "The value to set for the property on the device",
          "title": "Value",
          "type": "string"
        }
      },
      "required": [
        "device_label",
        "property_name",
        "value"
      ],
      "title": "PropertySetting",
      "type": "object"
    }
  }
}
```

</details>

### Benefits

1. **Validation**: Configurations can be verified against a formal schema before loading
1. **IDE Support**: Modern editors provide auto-completion, validation, and documentation for schema-based formats (i.e. if we put the schema on, for example, https://www.schemastore.org/json/, a user could get inline completion and hover-hints when editing the file)
1. **Readability**: YAML provides a human-readable format with full support for comments, (JSON could also be used, which is easier to parse, in C++, if a bit less readable)
1. **Extensibility**: The schema can be versioned and extended in a backward-compatible way
1. **Tooling**: Leverage existing JSON/YAML parsing libraries rather than maintaining custom parsers
1. **Documentation**: Schema includes descriptive fields and constraints for each property

## Implementation Path

The implementation would require:

1. **Finalizing the JSON Schema**.  The code defining the schema is here: https://github.com/tlambert03/mmcore-schema/blob/main/src/mmcore_schema/_mmconfig_schema.py.  We'd need to all agree on the structure of the schema obviously, and there's *plenty* to discuss there.
1. While not needed at runtime, I propose that the schema lives at <https://micro-manager.org/schemas/mmconfig/1.0/mmconfig.schema.json> ...
1. Implementing loaders in C++ (for core).  Python and Java loaders would be optional (that repo above would already work for python though).
1. Adding a conversion utility to/from existing .cfg files

### Example Implementation

A config file (for the [demo 2-photon config](https://github.com/micro-manager/mmCoreAndDevices/blob/main/DeviceAdapters/TwoPhoton/MMConfig_demo_two_photon.cfg#L203) might look like this:  

<details>

```yaml
schema_version: "1.0"
description: "Two Photon Demo Configuration"
date_created: "2025-05-07"

# Devices section
devices:
  - label: "DHub"
    library: "DemoCamera"
    name: "DHub"
  - label: "COM1"
    library: "SerialManager"
    name: "COM1"
  - label: "XY"
    library: "DemoCamera"
    name: "DXYStage"
  - label: "Shutter"
    library: "DemoCamera"
    name: "DShutter"
  - label: "BitFlowCamera"
    library: "TwoPhoton"
    name: "BitFlowCamera"
  - label: "Laser1"
    library: "TwoPhoton"
    name: "DemoLaser"
  - label: "EOM1"
    library: "NI100X"
    name: "AnalogIO"
  - label: "EOM2"
    library: "NI100X"
    name: "AnalogIO"
  - label: "EOM12Shutter"
    library: "TwoPhoton"
    name: "V2Shutter"
  - label: "Blue"
    library: "NI100X"
    name: "AnalogIO"
  - label: "Green"
    library: "NI100X"
    name: "AnalogIO"
  - label: "Yellow"
    library: "NI100X"
    name: "AnalogIO"
  - label: "Red"
    library: "NI100X"
    name: "AnalogIO"
  - label: "Laser2"
    library: "TwoPhoton"
    name: "DemoLaser"
  - label: "DObjective"
    library: "DemoCamera"
    name: "DObjective"
    state_labels:
      "0": "LowRes"
      "1": "HiRes"
      "2": "Objective-2"
      "3": "Objective-3"
      "4": "Objective-4"
      "5": "Objective-5"
  - label: "Z"
    library: "PI"
    name: "PIZStage"

# Pre-initialization properties
pre_init_properties:
  - device_label: "COM1"
    property_name: "AnswerTimeout"
    value: "500.0000"
  - device_label: "COM1"
    property_name: "BaudRate"
    value: "9600"
  - device_label: "COM1"
    property_name: "DelayBetweenCharsMs"
    value: "0.0000"
  - device_label: "COM1"
    property_name: "Handshaking"
    value: "Off"
  - device_label: "COM1"
    property_name: "Parity"
    value: "None"
  - device_label: "COM1"
    property_name: "StopBits"
    value: "1"
  - device_label: "EOM1"
    property_name: "IOChannel"
    value: "cDAQ1Mod1/ao0"
  - device_label: "EOM1"
    property_name: "MaxVolts"
    value: "5.0000"
  - device_label: "EOM1"
    property_name: "MinVolts"
    value: "0.0000"
  - device_label: "EOM1"
    property_name: "Demo"
    value: "Yes"
  - device_label: "EOM2"
    property_name: "IOChannel"
    value: "cDAQ1Mod1/ao1"
  - device_label: "EOM2"
    property_name: "MaxVolts"
    value: "5.0000"
  - device_label: "EOM2"
    property_name: "MinVolts"
    value: "0.0000"
  - device_label: "EOM2"
    property_name: "Demo"
    value: "Yes"
  - device_label: "Blue"
    property_name: "IOChannel"
    value: "cDAQ1Mod1/ao2"
  - device_label: "Blue"
    property_name: "MaxVolts"
    value: "10.0"
  - device_label: "Blue"
    property_name: "MinVolts"
    value: "0.0000"
  - device_label: "Blue"
    property_name: "Demo"
    value: "Yes"
  - device_label: "Green"
    property_name: "IOChannel"
    value: "cDAQ1Mod1/ao3"
  - device_label: "Green"
    property_name: "MaxVolts"
    value: "10.0"
  - device_label: "Green"
    property_name: "MinVolts"
    value: "0.0000"
  - device_label: "Green"
    property_name: "Demo"
    value: "Yes"
  - device_label: "Yellow"
    property_name: "IOChannel"
    value: "cDAQ1Mod1/ao4"
  - device_label: "Yellow"
    property_name: "MaxVolts"
    value: "10.0"
  - device_label: "Yellow"
    property_name: "MinVolts"
    value: "0.0000"
  - device_label: "Yellow"
    property_name: "Demo"
    value: "Yes"
  - device_label: "Red"
    property_name: "IOChannel"
    value: "cDAQ1Mod1/ao5"
  - device_label: "Red"
    property_name: "MaxVolts"
    value: "10.0"
  - device_label: "Red"
    property_name: "MinVolts"
    value: "0.0000"
  - device_label: "Red"
    property_name: "Demo"
    value: "Yes"
  - device_label: "Z"
    property_name: "MaxZ_um"
    value: "500.0000"
  - device_label: "Z"
    property_name: "Port"
    value: "COM1"
  - device_label: "Z"
    property_name: "WaitForResponse"
    value: "No"

# Core properties
core_properties:
  camera_device: "BitFlowCamera"
  shutter_device: "EOM12Shutter"
  focus_device: "Z"
  auto_shutter: true

# Configuration groups
configuration_groups:
  - name: "PIFoc"
    configurations:
      - name: "NewPreset"
        settings:
          - device_label: "Z"
            property_name: "Position"
            value: "0.0000"

  - name: "Color-Red"
    configurations:
      - name: "3"
        settings:
          - device_label: "BitFlowCamera"
            property_name: "R"
            value: "3"
      - name: "2"
        settings:
          - device_label: "BitFlowCamera"
            property_name: "R"
            value: "2"
      - name: "1"
        settings:
          - device_label: "BitFlowCamera"
            property_name: "R"
            value: "1"
      - name: "0"
        settings:
          - device_label: "BitFlowCamera"
            property_name: "R"
            value: "0"

  - name: "Channel"
    configurations:
      - name: "Green"
        settings:
          - device_label: "BitFlowCamera"
            property_name: "InputChannel"
            value: "1"
          - device_label: "EOM1"
            property_name: "ListIndex"
            value: "0"
          - device_label: "EOM2"
            property_name: "ListIndex"
            value: "0"
          - device_label: "Blue"
            property_name: "ListIndex"
            value: "0"
          - device_label: "Green"
            property_name: "ListIndex"
            value: "0"
          - device_label: "Yellow"
            property_name: "ListIndex"
            value: "0"
          - device_label: "Red"
            property_name: "ListIndex"
            value: "0"
      - name: "Red"
        settings:
          - device_label: "BitFlowCamera"
            property_name: "InputChannel"
            value: "3"
          - device_label: "EOM1"
            property_name: "ListIndex"
            value: "1"
          - device_label: "EOM2"
            property_name: "ListIndex"
            value: "1"
          - device_label: "Blue"
            property_name: "ListIndex"
            value: "1"
          - device_label: "Green"
            property_name: "ListIndex"
            value: "1"
          - device_label: "Yellow"
            property_name: "ListIndex"
            value: "1"
          - device_label: "Red"
            property_name: "ListIndex"
            value: "1"
      - name: "Yellow"
        settings:
          - device_label: "BitFlowCamera"
            property_name: "InputChannel"
            value: "2"
          - device_label: "EOM1"
            property_name: "ListIndex"
            value: "0"
          - device_label: "EOM2"
            property_name: "ListIndex"
            value: "0"
          - device_label: "Blue"
            property_name: "ListIndex"
            value: "0"
          - device_label: "Green"
            property_name: "ListIndex"
            value: "0"
          - device_label: "Yellow"
            property_name: "ListIndex"
            value: "0"
          - device_label: "Red"
            property_name: "ListIndex"
            value: "0"
      - name: "Blue"
        settings:
          - device_label: "BitFlowCamera"
            property_name: "InputChannel"
            value: "0"
          - device_label: "EOM1"
            property_name: "ListIndex"
            value: "0"
          - device_label: "EOM2"
            property_name: "ListIndex"
            value: "0"
          - device_label: "Blue"
            property_name: "ListIndex"
            value: "0"
          - device_label: "Green"
            property_name: "ListIndex"
            value: "0"
          - device_label: "Yellow"
            property_name: "ListIndex"
            value: "0"
          - device_label: "Red"
            property_name: "ListIndex"
            value: "0"

  - name: "System"
    configurations:
      - name: "Startup"
        settings:
          - device_label: "EOM12Shutter"
            property_name: "DAC1"
            value: "EOM1"
          - device_label: "EOM12Shutter"
            property_name: "DAC2"
            value: "EOM2"
          - device_label: "BitFlowCamera"
            property_name: "Deinterlace"
            value: "On+Warp"
          - device_label: "DObjective"
            property_name: "Label"
            value: "LowRes"

  - name: "Illumination"
    configurations:
      - name: "Sttings2"
        settings:
          - device_label: "EOM1"
            property_name: "Volts"
            value: "2.2950"
          - device_label: "EOM2"
            property_name: "Volts"
            value: "3.4050"
          - device_label: "Blue"
            property_name: "Volts"
            value: "5.2400"
          - device_label: "Green"
            property_name: "Volts"
            value: "2.8100"
          - device_label: "Yellow"
            property_name: "Volts"
            value: "5.8900"
          - device_label: "Red"
            property_name: "Volts"
            value: "3.4100"
      - name: "MySettings"
        settings:
          - device_label: "EOM1"
            property_name: "Volts"
            value: "0.6850"
          - device_label: "EOM2"
            property_name: "Volts"
            value: "1.4900"
          - device_label: "Blue"
            property_name: "Volts"
            value: "2.0600"
          - device_label: "Green"
            property_name: "Volts"
            value: "2.7800"
          - device_label: "Yellow"
            property_name: "Volts"
            value: "0.0000"
          - device_label: "Red"
            property_name: "Volts"
            value: "0.0000"

  - name: "Color-Green"
    configurations:
      - name: "3"
        settings:
          - device_label: "BitFlowCamera"
            property_name: "G"
            value: "3"
      - name: "2"
        settings:
          - device_label: "BitFlowCamera"
            property_name: "G"
            value: "2"
      - name: "1"
        settings:
          - device_label: "BitFlowCamera"
            property_name: "G"
            value: "1"
      - name: "0"
        settings:
          - device_label: "BitFlowCamera"
            property_name: "G"
            value: "0"

  - name: "Deinterlace"
    configurations:
      - name: "On"
        settings:
          - device_label: "BitFlowCamera"
            property_name: "Deinterlace"
            value: "On"
      - name: "On+Warp"
        settings:
          - device_label: "BitFlowCamera"
            property_name: "Deinterlace"
            value: "On+Warp"
      - name: "Off"
        settings:
          - device_label: "BitFlowCamera"
            property_name: "Deinterlace"
            value: "Off"

  - name: "Color-Blue"
    configurations:
      - name: "3"
        settings:
          - device_label: "BitFlowCamera"
            property_name: "B"
            value: "3"
      - name: "2"
        settings:
          - device_label: "BitFlowCamera"
            property_name: "B"
            value: "2"
      - name: "1"
        settings:
          - device_label: "BitFlowCamera"
            property_name: "B"
            value: "1"
      - name: "0"
        settings:
          - device_label: "BitFlowCamera"
            property_name: "B"
            value: "0"

  - name: "Camera"
    configurations:
      - name: "Demo"
        settings:
          - device_label: "BitFlowCamera"
            property_name: "Mode"
            value: "Demo"
      - name: "Hardware"
        settings:
          - device_label: "BitFlowCamera"
            property_name: "Mode"
            value: "Hardware"

  - name: "Offset"
    configurations:
      - name: "NewPreset"
        settings:
          - device_label: "BitFlowCamera"
            property_name: "CenterOffset"
            value: "0"

  - name: "Show PMT"
    configurations:
      - name: "3"
        settings:
          - device_label: "BitFlowCamera"
            property_name: "InputChannel"
            value: "3"
      - name: "2"
        settings:
          - device_label: "BitFlowCamera"
            property_name: "InputChannel"
            value: "2"
      - name: "1"
        settings:
          - device_label: "BitFlowCamera"
            property_name: "InputChannel"
            value: "1"
      - name: "0"
        settings:
          - device_label: "BitFlowCamera"
            property_name: "InputChannel"
            value: "0"

  - name: "Mode"
    configurations:
      - name: "RGB"
        settings:
          - device_label: "BitFlowCamera"
            property_name: "ColorMode"
            value: "RGB"
      - name: "Grayscale"
        settings:
          - device_label: "BitFlowCamera"
            property_name: "ColorMode"
            value: "Grayscale"
      - name: "Multichannel"
        settings:
          - device_label: "BitFlowCamera"
            property_name: "ColorMode"
            value: "Multichannel"

# Pixel size configurations
pixel_size_configurations:
  - name: "LowRes"
    pixel_size_um: 1.0
    settings:
      - device_label: "DObjective"
        property_name: "Label"
        value: "LowRes"
  
  - name: "HiRes"
    pixel_size_um: 0.5
    settings:
      - device_label: "DObjective"
        property_name: "Label"
        value: "HiRes"

# Optional metadata
extra:
  original_format: "CFG"
  original_creation_date: "2012-03-06T16:53:15-08:00"
  conversion_date: "2025-05-07"
  
```

</details>

... obviously, it's more verbose than the current format.  That could be dramatically simplified, but that would come at the expense of parsing complexity.  So, we'd want to discuss what format(s) we'd want to support before discussing how to change the syntax.

A Python implementation for loading the new format might look [like this](https://github.com/tlambert03/mmcore-schema/blob/main/README.md#pseudo-code)

Happy to hear your thoughts!

**Comment by tlambert03** [comment]
Already came up with an an alternative possible structure of the devices, to reduce the number of places that a device label has to be entered (and therefore decrease possible error).  It would nest props in with devices:

<details>

```yaml
# Device definitions
devices:
  - label: "DHub"
    library: "DemoCamera"
    name: "DHub"
    
  - label: "COM1"
    library: "SerialManager"
    name: "COM1"
    pre_init_properties:
      - property_name: "AnswerTimeout"
        value: "500.0000"
      - property_name: "BaudRate"
        value: "9600"
      - property_name: "DelayBetweenCharsMs"
        value: "0.0000"
      - property_name: "Handshaking"
        value: "Off"
      - property_name: "Parity"
        value: "None"
      - property_name: "StopBits"
        value: "1"
    
  - label: "XY"
    library: "DemoCamera"
    name: "DXYStage"
    
  - label: "Shutter"
    library: "DemoCamera"
    name: "DShutter"
    
  - label: "BitFlowCamera"
    library: "TwoPhoton"
    name: "BitFlowCamera"
    
  - label: "Laser1"
    library: "TwoPhoton"
    name: "DemoLaser"
    
  - label: "EOM1"
    library: "NI100X"
    name: "AnalogIO"
    pre_init_properties:
      - property_name: "IOChannel"
        value: "cDAQ1Mod1/ao0"
      - property_name: "MaxVolts"
        value: "5.0000"
      - property_name: "MinVolts"
        value: "0.0000"
      - property_name: "Demo"
        value: "Yes"
    
  - label: "EOM2"
    library: "NI100X"
    name: "AnalogIO"
    pre_init_properties:
      - property_name: "IOChannel"
        value: "cDAQ1Mod1/ao1"
      - property_name: "MaxVolts"
        value: "5.0000"
      - property_name: "MinVolts"
        value: "0.0000"
      - property_name: "Demo"
        value: "Yes"
```

</details>

anyway,  getting ahead of myself :)
